### ISSUE TITLE
event for playbackRate

### ISSUE THREAD

**Issue by Timibadass** [dobromir-hristov/vue-vimeo-player#17]
Hi, i'm trying to add a custom button to skip forward and backward by +10s and -10s respectively but I can't seem to find an event for it. I've tried using the event from the vimeo official docs **playbackratechange** and it still doesn't work. i'd like the full list of events , thanks.

**Comment by dobromir-hristov** [comment]
That is the rate, not skipping. Also you dont use events to control the player you use methods.

There is no out of the box method for this, you will need to do a combination of getting the current time, adding X seconds and then setting the time again.

Because we do not have this feature atm added in the wrapper, what you can do is:
Access the player via `$ref`, and then control from there.

```js
const player = this.$refs.vimeoPlayer.player
const currentTime = await player.getCurrentTime()
await player.setCurrentTime(currentTime + 10)
```

**Comment by Timibadass** [comment]
@dobromir-hristov thanks, this was helpful!
